name: tests

on:
  pull_request:
    branches: [main]

jobs:
  linting_and_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"
      - run: yarn install --immutable
      - run: yarn lint
      - run: yarn test
